### ISSUE TITLE
[TTS] Разработка модуля на основе существующего решения

### ISSUE THREAD

**Issue by VvVitekVvV** [citec-spbu/voice-assistant-patient-autumn2024#14]

**Comment by DanilKuznetcov** [comment]
- Было проведено исследование text to speech решений.
- В ходе сравнения основных претендентов pyttsx3 (статистический подход) и speakerpy (нейронные сети) - было отдано предпочтения второму из-за значительно лучшего качества. Результаты исследования выложены в ноутбуке
- На основе выбранного решения был разработан TTS блок + README файл с документацией по использованию
- Ветка с имплементированным решением была залита в репозиторий для возможности дальнейшего улучшения и смерджена с основной
