### ISSUE TITLE
[STT] Сравнительный анализ существующих решений

### ISSUE THREAD

**Issue by VvVitekVvV** [citec-spbu/voice-assistant-patient-autumn2024#7]

**Comment by nomatterwhoisthat** [comment]
В первую неделю интенсива пробовала разные модели для STT, искала в подходящий. Остановилась на Vosk Small. Попробовала сначала перевести речь из аудио в текст - получилось. Перешла на потоковое распознавание речи - получилось. Хотела перейти на сценарии, но без бд пока лишь можно выделять некоторые ключевые слова и всё. Начала работать над бд для проверки различных сценариев.
